version: '3.8'

x-base: &base
  build:
    context: .
    dockerfile: ./docker/Dockerfile
  env_file: .env
  volumes:
    - storage_data:/app/storage
  restart: always

services:
  rails:
    <<: *base
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - FORCE_SSL=true
      - DEFAULT_LOCALE=pt_BR
      - INTERNAL_HOST_URL=http://rails:3000
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-chatwoot}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-1556b5a7f48b5a440e1f7816133fbac70143289208c95cb4f90207aa48ee0555336d0a3cf6b78dd54833b3ab5517b91b9d5482473538651d32eea2669b3525b5}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-default_redis_password}@redis:6379
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    post_start:
      - command: "bundle exec rails db:prepare"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- --header='Accept: text/html' --header='X-Forwarded-Proto: https' http://127.0.0.1:3000/ || exit 1"]
      interval: 60s
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 1024M

  sidekiq:
    <<: *base
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - FORCE_SSL=true
      - DEFAULT_LOCALE=pt_BR
      - INTERNAL_HOST_URL=http://rails:3000
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE:-chatwoot}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-1556b5a7f48b5a440e1f7816133fbac70143289208c95cb4f90207aa48ee0555336d0a3cf6b78dd54833b3ab5517b91b9d5482473538651d32eea2669b3525b5}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-default_redis_password}@redis:6379
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep [s]idekiq || exit 1"]
      interval: 20s
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 512M

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chatwoot"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"${REDIS_PASSWORD:-default_redis_password}\""]
    env_file: .env
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"${REDIS_PASSWORD:-default_redis_password}\" ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  storage_data:
  postgres_data:
  redis_data:
